### ISSUE TITLE
Vergen crate requires a nightly Rust compiler

### ISSUE THREAD

**Issue by Technohacker** [Bauxitedev/bitmapflow#2]
The `vergen` crate used for version information seems to require a nightly compiler (as of version 1.50), and when everything using it was commented out it builds fine on stable Rust. Just wanted to mention it in case anyone faces the same issue :)

I haven't tested it with 1.51 yet, but maybe a mention about this in the README would help?

(Tested on Linux)

**Comment by Bauxitedev** [comment]
I have a file called `rust-toolchain` in the `rust` folder that should automatically cause Cargo to use the nightly toolchain. I guess it doesn't work if you don't have the toolchain installed. My intuition was that rustup would automatically download the nightly toolchain in that case, but I guess that doesn't work?

Anyway, I'll add a note in the README soon.

**Comment by Technohacker** [comment]
(Oh yeah I forgot to mention, I wasn't using rustup, I should've mentioned that, my bad :sweat_smile:)
