### ISSUE TITLE
Can't build 1.0.1 or 1.0.0 tags on Linux

### ISSUE THREAD

**Issue by DeeJayLSP** [Bauxitedev/bitmapflow#7]
But for some reason I can build main branch

It fails building bitmapflow-rust specifically

**Comment by Bauxitedev** [comment]
Can you post the error you get when compiling?

**Comment by DeeJayLSP** [comment]
Again, it only fails when building a non-main branch/tag:

```
error: failed to run custom build command for `bitmapflow-rust v1.0.1 (/home/user/Downloads/bitmapflow-1.0.1/rust)`

Caused by:
  process didn't exit successfully: `/home/user/Downloads/bitmapflow-1.0.1/rust/target/release/build/bitmapflow-rust-206946be4fbe6e7a/build-script-build` (exit code: 1)
  --- stderr
  Error: could not find repository from '/home/user/Downloads/bitmapflow-1.0.1/rust'; class=Repository (6); code=NotFound (-3)
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I literally just downloaded, extracted and ran `cargo build --release` on rust folder.

**Comment by Bauxitedev** [comment]
Did you download the repo as zip file? In that case try using `git clone` instead. (The build script requires a `.git`  folder to be present, which is not present when downloading the repo as zip)

**Comment by DeeJayLSP** [comment]
For the main one I actually used `git clone`, maybe that's why it worked.

The build seems to work on a cloned tag instead of source code downloaded as zip.

Also the one I've actually downloaded was a .tar.gz source code from the releases, not the repository. I don't get why a source code that you can't build would be distributed.

**Comment by Bauxitedev** [comment]
> I don't get why a source code that you can't build would be distributed.

Just because a build dependency is not mentioned in the documentation, doesn't mean "the source code can't be built".

Anyway, I'll add this to the README.

**Comment by DeeJayLSP** [comment]
Well, I'm glad we came to a solution, thanks for documenting it
